src/config/routes.rb
Rails.application.routes.draw do
  resources :movies
  devise_for :users
  resources :categories
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts # localhost:3000/posts

  #Routes gestion erreur
  get '/errors', to: 'errors#index'

  #Route / ou /home
  get '/home', '/', to: 'home#index'

  #Route backoffice Admin
  get '/users', to: 'users#index'
  get '/users/change_status_admin', to: 'users#change_status_admin'
  get '/users/change_status_user', to: 'users#change_status_user'
  
  #Route poru la location
  get '/rent', to: 'movies#rent'
  get '/unrent', to: 'movies#unrent'
  get '/rent_show', to: 'movies#rent_show'

end

src/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    authorize! :read, Movie
    @movies = Movie.all
  end

  def rent_show
    authorize! :manage, Movie
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    authorize! :manage, Movie
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    authorize! :manage, Movie
  end

  # POST /movies
  # POST /movies.json
  def create
    authorize! :manage, Movie
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    authorize! :update, Movie
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def rent
    authorize! :update, Movie
    @movie = Movie.find(params[:id])
    @movie.update status: true
    redirect_to '/movies'
  end

  def unrent
    authorize! :manage, Movie
    @movie = Movie.find(params[:id])
    @movie.update status: false
    redirect_to '/movies'
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    authorize! :manage, Movie
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :producer, :description, :release_date, :status, :user_id)
    end
end

src/app/helpers/movies_helper.rb
module MoviesHelper
end

src/app/views/movies/_form.html.erb
<p id="notice"><%= notice %></p>

<% user ||= current_user %>


<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field" style="display:none;">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="field" style="display:none;">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/movies/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing movie</h1>

<ul>
  <li> <%= link_to("Accueil", "/home") %> </li>
  <% if user_signed_in?  %>
  <li>Compté connecté : <%= current_user.email %> </li>
  <li> <%= link_to("Voir les films", "/movies") %> </li>
  <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <li> <%= link_to("Utilisateurs", "/users") %> </li>
  <% else  %>
  <li>  <%= link_to("Login", new_user_session_path) %></li>
  <li>  <%= link_to("Inscription", new_user_registration_path) %></li>
  <% end  %>
</ul>


<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

src/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<% user ||= current_user %>

<h1>Movies</h1>

<ul>
  <li> <%= link_to("Accueil", "/home") %> </li>
  <% if user_signed_in?  %>
  <li>Compté connecté : <%= current_user.email %> </li>
  <li> <%= link_to("Voir les films", "/movies") %> </li>
  <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <% if user.admin? %>
  <li> <%= link_to("Utilisateurs", "/users") %> </li>
  <% end %>
  <% else  %>
  <li>  <%= link_to("Login", new_user_session_path) %></li>
  <li>  <%= link_to("Inscription", new_user_registration_path) %></li>
  <% end  %>
</ul>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Producer</th>
      <th>Description</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie|
      unless movie.status == true %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.producer %></td>
        <td><%= movie.description %></td>
        <td><%= movie.release_date %></td>
        <% if user.admin? %>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td><%= link_to 'Rent', controller: "movies", action: "rent", id: movie.id %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user.admin? %>
<%= link_to 'Movie rent', '/rent_show' %>
<br>
<%= link_to 'New Movie', new_movie_path %>
<% end %>

src/app/views/movies/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New movie</h1>

<ul>
  <li> <%= link_to("Accueil", "/home") %> </li>
  <% if user_signed_in?  %>
  <li>Compté connecté : <%= current_user.email %> </li>
  <li> <%= link_to("Voir les films", "/movies") %> </li>
  <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <li> <%= link_to("Utilisateurs", "/users") %> </li>
  <% else  %>
  <li>  <%= link_to("Login", new_user_session_path) %></li>
  <li>  <%= link_to("Inscription", new_user_registration_path) %></li>
  <% end  %>
</ul>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

src/app/views/movies/rent_show.html.erb
<p id="notice"><%= notice %></p>

<% user ||= current_user %>

<h1>Rented movies</h1>

<ul>
  <li> <%= link_to("Accueil", "/home") %> </li>
  <% if user_signed_in?  %>
  <li>Compté connecté : <%= current_user.email %> </li>
  <li> <%= link_to("Voir les films", "/movies") %> </li>
  <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <% if user.admin? %>
  <li> <%= link_to("Utilisateurs", "/users") %> </li>
  <% end %>
  <% else  %>
  <li>  <%= link_to("Login", new_user_session_path) %></li>
  <li>  <%= link_to("Inscription", new_user_registration_path) %></li>
  <% end  %>
</ul>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Producer</th>
      <th>Description</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie|
      unless movie.status == false %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.producer %></td>
        <td><%= movie.description %></td>
        <td><%= movie.release_date %></td>
        <% if user.admin? %>
        <td><%= link_to 'Unrent', controller: "movies", action: "unrent", id: movie.id %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

src/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<ul>
  <li> <%= link_to("Accueil", "/home") %> </li>
  <% if user_signed_in?  %>
  <li>Compté connecté : <%= current_user.email %> </li>
  <li> <%= link_to("Voir les films", "/movies") %> </li>
  <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <li> <%= link_to("Utilisateurs", "/users") %> </li>
  <% else  %>
  <li>  <%= link_to("Login", new_user_session_path) %></li>
  <li>  <%= link_to("Inscription", new_user_registration_path) %></li>
  <% end  %>
</ul>
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @movie.producer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>