src/config/routes.rb
Rails.application.routes.draw do
  resources :movies
  devise_for :users
  resources :categories
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts # localhost:3000/posts

  #Routes gestion erreur
  get '/errors', to: 'errors#index'

  #Route / ou /home
  get '/home', '/', to: 'home#index'

  #Route backoffice Admin
  get '/users', to: 'users#index'
  get '/users/change_status_admin', to: 'users#change_status_admin'
  get '/users/change_status_user', to: 'users#change_status_user'
  
  #Route poru la location
  get '/rent', to: 'movies#rent'
  get '/unrent', to: 'movies#unrent'
  get '/rent_show', to: 'movies#rent_show'

end

src/app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content
  validates :content, length: { minimum: 10 }
  validates :status, inclusion: { in: [true, false] }

  has_many :comments, dependent: :delete_all

  has_and_belongs_to_many :categories
end

src/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :category_list, only: [:new, :edit]

  before_action :authenticate_user!, only: [:new, :create]

  # GET /posts
  def index
  @posts = Post.all
  end

  # GET /posts/1
  def show
    @comments = Comment.where(post_id: params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post created'
    else
      render :new
    end
  end

  # GET /posts/1/edit
  def edit
  end


  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post updated'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post destroyed"
  end

  private

  def set_post
     @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :status, category_ids: [])
  end

  def category_list
    @categories = Category.all
  end
end

src/app/helpers/posts_helper.rb
module PostsHelper
  def post_status_label(boolean)
    boolean ? "Public" : "Brouillon"
  end

  def post_categories_label(categories)
    raw categories.map { |cat|
      "<span class='badge' style='color:#fff;background-color:#{cat.color};'>#{cat.name}</span>"
      } .join(', ')
    end
  end

src/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>

<% if post.errors.any? %>
<div>
  <h2>There is <%= pluralize(post.errors.count, "error") %></h2>
  <ul>
    <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :content %>
  <%= form.text_field :content %>
</div>

<div>
  <%= form.label :status %>
  <%= form.select :status, [ ['Brouillon', false], ["Public", true] ], selected: post.status ? post.status : false %>
</div>

<div>
  <%= form.label :category_ids %>
  <%= form.collection_check_boxes(:category_ids, @categories, :id, :name) %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

src/app/views/posts/edit.html.erb
<h1>Update post</h1>

<%= render 'form', post: @post %>

<%= link_to("Liste articles", posts_path) %>

src/app/views/posts/index.html.erb
<h1>Posts</h1>

<p> <%= notice %> </p>

<ul>
  <li> <%= link_to("Accueil", "/home") %> </li>
  <% if user_signed_in?  %>
  <li>Compté connecté : <%= current_user.email %> </li>
  <li> <%= link_to("Voir les films", "/movies") %> </li>
  <li> <%= link_to("Voir les posts", "/posts") %> </li>
  <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  <% else  %>
  <li>  <%= link_to("Login", new_user_session_path) %></li>
  <li>  <%= link_to("Inscription", new_user_registration_path) %></li>
  <% end  %>
</ul>

<table>

  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th>Catégories</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td> <%= post.title %> </td>
      <td> <%= post.content %> </td>
      <td> <%= post_categories_label(post.categories) %> </td>
      <td> <%= post_status_label(post.status) %> </td>
      <td> <%= link_to('Show', post) %> </td>
      <td> <%= link_to('Edit', edit_post_path(post)) %> </td>
      <td> <%= link_to('Destroy', post, method: :delete, data: { confirm: 'Supprimer ?' }) %> </td>
    </tr>
    <% end %>
  </tbody>

</table>

<%= link_to "New post", new_post_path %>

src/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form', post: @post %>

<%= link_to("Liste articles", posts_path) %>

src/app/views/posts/show.html.erb
<p> <%= notice %> </p>

<p>Title : <%= @post.title %></p>
<p>Content : <%= @post.content %></p>
<p>Status : <%= post_status_label(@post.status) %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.message %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "Liste articles", posts_path %>